name: nanen
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-362.0.dev <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  ## STATE MANAGEMENT
  get: ^4.6.5

  ## ONBOARDING PACKAGE
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.0.1

  line_awesome_flutter : ^2.0.0
  google_fonts: ^4.0.3
  flutter_native_splash: ^2.2.19
  
  flutter_otp_text_field: ^1.1.1

  ## login
  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.1
  google_sign_in: ^5.4.4
  kakao_flutter_sdk: ^1.4.3
  http: ^0.13.6
  cloud_firestore: ^4.8.0


  percent_indicator: ^4.0.1
  carousel_slider: ^4.2.1
  fl_chart: ^0.62.0
  collection: ^1.17.1
  cached_network_image: ^3.2.3
  syncfusion_flutter_charts: ^21.2.5
  masonry_grid: ^1.0.0
  flutter_staggered_grid_view: ^0.6.2

  image_picker: ^0.8.7+4
  path_provider: ^2.0.15
  syncfusion_flutter_calendar: ^21.2.4
    # handle dates
  intl: ^0.18.1

  # state management
  provider: ^6.0.5
  
  url_launcher: ^6.0.9

  # image upload
  image_cropper: ^1.4.1 
  flutter_image_compress: ^1.0.0


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  font_awesome_flutter: ^10.5.0
  intl: ^0.18.1
  url_launcher: ^6.1.12
  vector_math: ^2.1.4

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/mini.jpg
  image_dark: assets/images/mini.jpg
  android: true
  ios: true

  android_12:
    image: assets/images/mini.jpg
    icon_background_color: "#f7f6f1"
    image_dark: assets/images/mini.jpg
    icon_background_color_dark: "#272727"

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/images/splash_images/
    - assets/images/on_boarding_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/
    - assets/images/dashboard/
    - assets/images/home/
    - assets/images/mission/
    - assets/images/profile/
    - assets/images/login/
    - assets/fitness_app/


    # - assets/images/tabbarview/
    # - assets/images/tabbarview/active
    # - assets/images/tabbarview/calm



  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
