// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEwuOD-ZhExezYPd4k4XHGUIzcfsJiUGQ',
    appId: '1:1098987290110:web:9d9638242e04aa280794af',
    messagingSenderId: '1098987290110',
    projectId: 'flutter-login-app-8b654',
    authDomain: 'flutter-login-app-8b654.firebaseapp.com',
    storageBucket: 'flutter-login-app-8b654.appspot.com',
    measurementId: 'G-Y5BM4SM1J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv6kwTg0XQcrkZtJH9VVE1OjYPSnLc5j0',
    appId: '1:1098987290110:android:ac49f11b17282b610794af',
    messagingSenderId: '1098987290110',
    projectId: 'flutter-login-app-8b654',
    storageBucket: 'flutter-login-app-8b654.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbxR4LW2dwBkAgC9mv6jKCjHBT9szGy2M',
    appId: '1:1098987290110:ios:fd4168defda5bdff0794af',
    messagingSenderId: '1098987290110',
    projectId: 'flutter-login-app-8b654',
    storageBucket: 'flutter-login-app-8b654.appspot.com',
    androidClientId: '1098987290110-chaj8o3r9mnikh20ev2c8ldkj7in99rn.apps.googleusercontent.com',
    iosClientId: '1098987290110-hnhkvoa4d27vmi7o68u52d27fnq04b0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.nanen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbxR4LW2dwBkAgC9mv6jKCjHBT9szGy2M',
    appId: '1:1098987290110:ios:a934656fdc3c139f0794af',
    messagingSenderId: '1098987290110',
    projectId: 'flutter-login-app-8b654',
    storageBucket: 'flutter-login-app-8b654.appspot.com',
    androidClientId: '1098987290110-chaj8o3r9mnikh20ev2c8ldkj7in99rn.apps.googleusercontent.com',
    iosClientId: '1098987290110-sbt5cu6r1aeis9njqrn6avstmjh3cik6.apps.googleusercontent.com',
    iosBundleId: 'com.example.nanen.RunnerTests',
  );
}
